# The sequence of triangle numbers is generated by adding the natural numbers. 
# So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten terms would be:
# 1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...
# Let us list the factors of the first seven triangle numbers:
#  1: 1
#  3: 1,3
#  6: 1,2,3,6
# 10: 1,2,5,10
# 15: 1,3,5,15
# 21: 1,3,7,21
# 28: 1,2,4,7,14,28
# We can see that 28 is the first triangle number to have over five divisors.
# What is the value of the first triangle number to have over five hundred divisors?



def DivisorNumber(target_number):
	divisor_number_dict = {}
	looping = True
	# while looping:
	while True:
		i = 2
		while target_number != 1:
			# if target_number % i != 0:
			if target_number % i == 0:
				if i not in divisor_number_dict:
					print i
					divisor_number_dict[i] = 1
				elif i in divisor_number_dict:
					print i
					divisor_number_dict[i] += 1
				target_number /= i
			if 	target_number == 1:
				looping = False

		i += 1
		
	print divisor_number_dict		
	prodocut = 1		
	for values in divisor_number_dict.values():
		prodocut *= (values + 1)

	return prodocut	






running = True
start_number = 1
triangle_number = 1
while running:

	dn = DivisorNumber(triangle_number)
	start_number += 1
	triangle_number += start_number
	print triangle_number,dn
	

	if dn > 500:
		running = False
	
